import { Sidebar } from "@/app/_components";
import { Box } from "@mui/material";
import { Providers } from "./_providers";
import "./globals.css";

export const metadata = {
  title: "List Data App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Providers>
          <Box display={"flex"}>
            <Sidebar />
            <Box
              sx={{
                flexGrow: 1,
                overflow: "hidden",
              }}
            >
              {children}
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
